"""
Create a class Student that has the following attributes:

- `first_name` - the first name of the student
- `last_name` - the last name of the student
- `id` - the class id of the student (a positive integer)
- `grades` - a list of the student grades

Using a class attribute find a way to make the id `auto incremental`
(when a new student instance is create the id will be autogenerated)

Example:

```python
class Student:
    pass


# Create a new list of students
students = [
    Student("Ivan", "Dimitrov"),
    Student("Dimitar", "Ivanov"),
]

for student_index in range(len(students)):
    assert students[student_index].id == student_index + 1
```
"""


class Student:
    id_auto_increment = 1

    def __init__(self, first_name: str, last_name: str):
        self.first_name = first_name
        self.last_name = last_name
        self.id = self.id_auto_increment
        self.grades = []

        # Don't forget to auto increment the class attribute
        Student.id_auto_increment += 1


if __name__ == "__main__":

    students = [
        Student("Ivan", "Dimitrov"),
        Student("Dimitar", "Ivanov"),
    ]

    for student_index in range(len(students)):
        print(students[student_index].id)
        assert students[student_index].id == student_index + 1
